### ISSUE TITLE
directory and filepath lower bounds

### ISSUE THREAD

**Issue by ljli** [ocharles/tasty-ant-xml#19]
#16 introduces dependencies on directory and filepath with lower bounds that preclude this package from being build with GHC < 8.0.1. Given the content of the commit that seems excessive.

**Comment by ocharles** [comment]
You're right. From looking at version 1.0 of these packages, they export the API we require. Assuming these functions weren't removed and then re-added, we should be good with this lower bound. I'll run with that assumption and lower the bounds now.

**Comment by ocharles** [comment]
Released as 1.0.5.

**Comment by liskin** [comment]
Not a good idea. Old versions of `directory` (pre-1.2.3.0) throw exceptions if the argument passed to `canonicalizePath` does not exist, so using `--xml nonexistentfile.xml` fails: https://travis-ci.org/IxpertaSolutions/tasty-jenkins-xml/jobs/206104092

**Comment by ocharles** [comment]
Thanks @liskin, I'll get this fixed.

**Comment by ocharles** [comment]
Bumped to 1.2.3.0 in `tasty-ant-xml-1.1.0`.
