### ISSUE TITLE
tasty-1.1

### ISSUE THREAD

**Issue by ozgurakgun** [ocharles/tasty-ant-xml#24]
tasty-1.1 was released (very) recently. Should the upper bound be changed for tasty-ant-xml to allow it?

As far as I can see, there isn't anything else that needs changing.

**Comment by ocharles** [comment]
Yea, I just got a notification that the bounds need to be bumped. It looks like a small minor change that shouldn't affect this. I'll probalby be looking at this in the week.

**Comment by ozgurakgun** [comment]
Great. No rush, I just wanted to flag it up in case you hadn't seen it.

**Comment by ocharles** [comment]
Fixed and released to Hackage.
