### ISSUE TITLE
Stackage

### ISSUE THREAD

**Issue by sergv** [ocharles/tasty-ant-xml#25]
Are there any plans to make this package available on stackage?

**Comment by ocharles** [comment]
Yea, I don't mind doing that. Should be able to get to that soon, or feel
free to submit on behalf

**Comment by sergv** [comment]
Thanks, I'll do the submission.

**Comment by ocharles** [comment]
Cheers, please link back here once you're done. Thanks!

**Comment by sergv** [comment]
Sure, https://github.com/commercialhaskell/stackage/pull/3687. Thanks!

**Comment by ocharles** [comment]
Looks like that merged. Thanks!
